//  Admin Actions
const GET_PROBLEM = 'GET_PROBLEM'
const ADD_PROBLEM = 'ADD_PROBLEM'
const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
const GET_PROBLEMS = 'GET_PROBLEMS'
const GET_PARTICIPANTS = 'GET_PARTICIPANTS'
const DELETE_PROBLEM = 'DELETE_PROBLEM'
const INITIALIZE_PROBLEMS = 'INITIALIZE_PROBLEMS'
const PROBLEM_LOADING = 'PROBLEM_LOADING'

// Tests Actions
const GET_TESTS = 'GET_TESTS'
const SET_TESTS = 'SET_TESTS'
const DELETE_TEST = 'DELETE_TEST'
const TEST_LOADING = 'TEST_LOADING'
const CATEGORY_LOADING = 'CATEGORY_LOADING'
const GET_INDEX = 'GET_INDEX'
const GET_TOPNUM = 'GET_TOPNUM'
const GET_CATEGORY = 'GET_CATEGORY'

// Answer Actions
const ADD_ANSWER = 'ADD_ANSWER'
const UPDATE_ANSWER = 'UPDATE_ANSWER'
const CLEAR_ANSWER = 'CLEAR_ANSWER'
const INCREASE_CHEATNUM = 'INCREASE_CHEATNUM'

export {
  GET_PROBLEM,
  ADD_PROBLEM,
  UPDATE_PROBLEM,
  DELETE_PROBLEM,
  GET_PROBLEMS,
  GET_PARTICIPANTS,
  INITIALIZE_PROBLEMS,
  PROBLEM_LOADING,

  GET_TESTS,
  SET_TESTS,
  DELETE_TEST,
  GET_INDEX,
  GET_TOPNUM,
  TEST_LOADING,
  CATEGORY_LOADING,
  GET_CATEGORY,

  ADD_ANSWER,
  UPDATE_ANSWER,
  CLEAR_ANSWER,
  INCREASE_CHEATNUM,
}