const JWT_SECRET = process.env.JWT_SECRET || 'drivingwebapp'
const categories = [
  'category 0.1',
  'category 1.1',
  'category 1.2',
  'category 1.3',
  'category 1.4',
  'category 1.5',
  'category 2.1',
  'category 2.2',
  'category 2.3',
  'category 2.4',
  'category 2.5',
  'category 2.6',
  'category 2.7',
  'category 2.8',
  'category 3.1',
  'category 3.2',
  'category 3.3',
  'category 3.4',
  'category 3.5',
  'category 3.6',
  'category 3.7',
  'category 3.8',
  'category 4.1',
  'category 5.1',
  'category 6.1',
  'category 7.1',
  'category 7.2',
  'category 7.3',
  'category 7.4',
  'category 8.1',
  'category 9.1',
  'category 10.1',
]

module.exports = {
  JWT_SECRET,
  categories,
}